### ISSUE TITLE
Installation issue with pysam

### ISSUE THREAD

**Issue by aubinthomas** [CollasLab/edd#1]
Hello,

I'm trying to install EDD software. I installed all the requirements. But during the installation process I have an error :
###### 

Traceback (most recent call last):
         File "<string>", line 17, in <module>
         File "/tmp/pip_build_root/edd/setup.py", line 22, in <module>
           but the installed version was %s. Please upgrade pysam.''' % pysam.__version)
       AttributeError: 'module' object has no attribute '__version'
       Complete output from command python setup.py egg_info:
       Traceback (most recent call last):

```
File "<string>", line 17, in <module>

File "/tmp/pip_build_root/edd/setup.py", line 22, in <module>

but the installed version was %s. Please upgrade pysam.''' % pysam.__version)
```

AttributeError: 'module' object has no attribute '__version'
###### 

Here is the list of the packages I have : 
###### 

$ pip freeze
Cython==0.21.1
Django==1.7.1
Logbook==0.8.0
MACE==1.1
MACS==2.0.9
Mako==0.9.1
Markdown==2.4
MarkupSafe==0.18
PAM==0.4.2
Pillow==2.3.0
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
apt-xapian-index==0.45
apturl==0.4.1ubuntu4
argparse==1.2.1
bitsets==0.7.8
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
configglue==1.1.2
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
django-tables2==0.15.0
dnspython==1.11.1
docutils==0.11
duplicity==0.6.23
feedparser==5.1.3
genomes==1.1.0
html5lib==0.999
httplib2==0.8
lockfile==0.8
lxml==3.3.3
matplotlib==1.3.1
miro==4.0.4
mutagen==1.22
numpy==1.9.1
oauthlib==0.6.1
oneconf==0.3.7
panda==0.1.5
pandas==0.15.1
paramiko==1.10.1
patsy==0.3.0
pexpect==3.1
piston-mini-client==0.7.5
protobuf==2.5.0
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pyinotify==0.9.4
pyparsing==2.0.1
pysam==0.8.0
pyserial==2.6
pysmbc==1.0.14.1
pysqlite==2.6.3
python-apt==0.9.3.5
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
python-libtorrent==0.16.13
pytz==2012c
pyxdg==0.25
reportlab==3.0
requests==2.2.1
roman==2.0.0
rpy==1.0.3
scipy==0.14.0
sessioninstaller==0.0.0
setuptools-git==1.0b1
six==1.5.2
statsmodels==0.6.0
system-service==0.1.6
textile==2.1.5
track==1.3.0-dev
uTidylib==0.2
urllib3==1.7.1
vboxapi==1.0
wsgiref==0.1.2
zope.interface==4.0.5
###### 

I'm working on Linux Mint 17, but I have exactly the same issue on Debian Wheezy (7.7)

Thanks in advance

**Comment by eivindgl** [comment]
Hi,
Sorry for this very late reply. I have completely overlooked this message and I saw it just now by accident.  I have just updated EDD and hopefully fixed your problem as well. If it is still interesting.
all the best,
eivind
