### ISSUE TITLE
Add quick start example

### ISSUE THREAD

**Issue by endrebak** [CollasLab/edd#10]
Would be nice if you could add some small files edd works on to this repo so people can download and try the program easily. 

This will also help them understand exactly what the files are supposed to look like.

**Comment by ajphipps** [comment]
I agree! It would also be great for more complete documentation with an example of running the tool (an eg or similar) with all variables and required files.

**Comment by endrebak** [comment]
I could never get EDD to work though, and I am about as proficient a Python bioinformatics programmer as you could get :/

**Comment by endrebak** [comment]
Seems like the project is abandoned.
